/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const mockCurrentUser: typeof import('@redwoodjs/testing/web')['mockCurrentUser']
  const mockGraphQLMutation: typeof import('@redwoodjs/testing/web')['mockGraphQLMutation']
  const mockGraphQLQuery: typeof import('@redwoodjs/testing/web')['mockGraphQLQuery']
}
